pipeline {
    agent any

    tools {
        maven 'Maven-3.9'
        jdk 'jdk-21'
    }

    stages {

        stage('Run Tests') {
            steps {
                bat 'mvn clean test'
            }
        }

        stage('Publish Report') {
            steps {
                publishHTML(target: [
                    allowMissing: false,
                    alwaysLinkToLastBuild: true,
                    keepAll: true,
                    reportDir: 'target/cucumber-reports',
                    reportFiles: 'index.html',
                    reportName: 'Cucumber Test Report'
                ])
            }
        }
    }

    post {
        always {
            echo "🔁 Build complete"
        }
    }
}
