pipeline {
    agent any

    tools {
        maven 'Maven-3.9'
        jdk 'jdk-21'
    }

    stages {
        stage('Debug') {
            steps {
                echo '✅ Jenkinsfile loaded and executing'
            }
        }

        stage('Run Tests') {
            steps {
                bat 'mvn clean test'
            }
        }
    }

    post {
        always {
            echo '🔁 Build complete'
        }
    }
}
